# Generated by Django 5.0.6 on 2024-06-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Countapp', '0002_record_msec'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='certifications/')),
                ('description', models.TextField()),
            ],
        ),
    ]
