# Generated by Django 4.2.5 on 2024-07-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountapp', '0004_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_img',
            field=models.ImageField(default=None, upload_to='profiles_img/'),
        ),
    ]
