# Generated by Django 4.2.5 on 2024-07-05 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Countapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Countapp.record'),
        ),
    ]
