# Generated by Django 5.0.6 on 2024-07-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Countapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
