# Generated by Django 5.0.6 on 2024-07-05 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Countapp', '0002_certification_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='title',
        ),
    ]
