# Generated by Django 4.2.5 on 2024-07-04 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Countapp', '0007_rename_image_certification_walk_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Countapp.record'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='archive_image',
            field=models.ImageField(blank=True, null=True, upload_to='archives/'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
