# Generated by Django 5.0.6 on 2024-07-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicarchive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicarchive',
            name='author',
        ),
        migrations.RemoveField(
            model_name='musicarchive',
            name='created_at',
        ),
        migrations.AddField(
            model_name='musicarchive',
            name='image1',
            field=models.ImageField(default=None, upload_to='musicarchive/images/'),
        ),
        migrations.AddField(
            model_name='musicarchive',
            name='image2',
            field=models.ImageField(default=None, upload_to='musicarchive/images/'),
        ),
    ]
