# Generated by Django 5.0.6 on 2024-07-02 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicarchive', '0002_remove_musicarchive_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicarchive',
            name='image2',
        ),
    ]
